/* Generated By:JavaCC: Do not edit this line. LibParserConstants.java */
package lib;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LibParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int LIBRARY = 9;
  /** RegularExpression Id. */
  int WEBSITE = 10;
  /** RegularExpression Id. */
  int BUILDING = 11;
  /** RegularExpression Id. */
  int TIME_OF_YEAR = 12;
  /** RegularExpression Id. */
  int START = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int HOURS = 15;
  /** RegularExpression Id. */
  int CLOSED = 16;
  /** RegularExpression Id. */
  int STAFF = 17;
  /** RegularExpression Id. */
  int POSITION = 18;
  /** RegularExpression Id. */
  int EMAIL = 19;
  /** RegularExpression Id. */
  int TYPE = 20;
  /** RegularExpression Id. */
  int RATE = 21;
  /** RegularExpression Id. */
  int BOOK_COLLECTION = 22;
  /** RegularExpression Id. */
  int BOOK = 23;
  /** RegularExpression Id. */
  int TITLE = 24;
  /** RegularExpression Id. */
  int AUTHOR = 25;
  /** RegularExpression Id. */
  int TO = 26;
  /** RegularExpression Id. */
  int LPAREN = 27;
  /** RegularExpression Id. */
  int RPAREN = 28;
  /** RegularExpression Id. */
  int LBRACE = 29;
  /** RegularExpression Id. */
  int RBRACE = 30;
  /** RegularExpression Id. */
  int LBRACKET = 31;
  /** RegularExpression Id. */
  int RBRACKET = 32;
  /** RegularExpression Id. */
  int QUOTE = 33;
  /** RegularExpression Id. */
  int COLON = 34;
  /** RegularExpression Id. */
  int SEMICOLON = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int FULLSTOP = 37;
  /** RegularExpression Id. */
  int HYPHEN = 38;
  /** RegularExpression Id. */
  int UNDERSCORE = 39;
  /** RegularExpression Id. */
  int AT = 40;
  /** RegularExpression Id. */
  int DOLLAR = 41;
  /** RegularExpression Id. */
  int FORWARDSLASH = 42;
  /** RegularExpression Id. */
  int LABEL = 43;
  /** RegularExpression Id. */
  int BUILDING_NUMBER = 44;
  /** RegularExpression Id. */
  int TYPE_OPTION = 45;
  /** RegularExpression Id. */
  int RATE_VALUE = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int DIGIT = 48;
  /** RegularExpression Id. */
  int WEBSITE_ADDRESS = 49;
  /** RegularExpression Id. */
  int PROTOCOL = 50;
  /** RegularExpression Id. */
  int ADDRESS = 51;
  /** RegularExpression Id. */
  int YEAR = 52;
  /** RegularExpression Id. */
  int MONTH = 53;
  /** RegularExpression Id. */
  int LEAP_MONTH = 54;
  /** RegularExpression Id. */
  int NORMAL_MONTH = 55;
  /** RegularExpression Id. */
  int FEBRUARY = 56;
  /** RegularExpression Id. */
  int DAY = 57;
  /** RegularExpression Id. */
  int WEEK = 58;
  /** RegularExpression Id. */
  int WEEK_SHORT = 59;
  /** RegularExpression Id. */
  int TIME = 60;
  /** RegularExpression Id. */
  int EMAIL_ADDRESS = 61;
  /** RegularExpression Id. */
  int LOCAL_PART = 62;
  /** RegularExpression Id. */
  int DOMAIN_PART = 63;
  /** RegularExpression Id. */
  int BOOK_ID = 64;
  /** RegularExpression Id. */
  int BOOK_TITLE = 65;
  /** RegularExpression Id. */
  int SHORT_NAME = 66;
  /** RegularExpression Id. */
  int LONG_NAME = 67;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"LIBRARY\"",
    "\"WEBSITE\"",
    "\"BUILDING\"",
    "\"TIMEOFYEAR\"",
    "\"START\"",
    "\"END\"",
    "\"HOURS\"",
    "\"CLOSED\"",
    "\"STAFF\"",
    "\"POSITION\"",
    "\"EMAIL\"",
    "\"TYPE\"",
    "\"RATE\"",
    "\"BOOKCOLLECTION\"",
    "\"BOOK\"",
    "\"TITLE\"",
    "\"AUTHOR\"",
    "\"to\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"-\"",
    "\"_\"",
    "\"@\"",
    "\"$\"",
    "\"/\"",
    "<LABEL>",
    "<BUILDING_NUMBER>",
    "<TYPE_OPTION>",
    "<RATE_VALUE>",
    "<LETTER>",
    "<DIGIT>",
    "<WEBSITE_ADDRESS>",
    "<PROTOCOL>",
    "<ADDRESS>",
    "<YEAR>",
    "<MONTH>",
    "<LEAP_MONTH>",
    "<NORMAL_MONTH>",
    "\"February\"",
    "<DAY>",
    "<WEEK>",
    "<WEEK_SHORT>",
    "<TIME>",
    "<EMAIL_ADDRESS>",
    "<LOCAL_PART>",
    "<DOMAIN_PART>",
    "<BOOK_ID>",
    "<BOOK_TITLE>",
    "<SHORT_NAME>",
    "<LONG_NAME>",
    "\"AM\"",
    "\"PM\"",
  };

}
